import type { BrainDoc, Conversation, SearchResult, Integration, ActivityItem, User } from '@/types';

export const currentUser: User = {
  id: 'u1',
  name: 'Alex Morgan',
  email: 'alex.morgan@example.com',
};

export const mockDocuments: BrainDoc[] = [
  {
    id: 'd1',
    name: 'Q3 Financial Report.pdf',
    type: 'pdf',
    size: 2458624,
    status: 'indexed',
    createdAt: '2025-08-10T09:30:00Z',
    updatedAt: '2025-08-10T09:35:00Z',
    summary: 'Comprehensive Q3 financial analysis covering revenue growth, expense breakdown, and forward-looking projections for Q4.',
    pageCount: 42,
    tags: ['finance', 'reports'],
  },
  {
    id: 'd2',
    name: 'Product Roadmap 2025.docx',
    type: 'docx',
    size: 187392,
    status: 'indexed',
    createdAt: '2025-08-09T14:20:00Z',
    updatedAt: '2025-08-09T14:25:00Z',
    summary: 'Strategic product roadmap outlining key milestones, feature releases, and technical debt resolution through 2025.',
    pageCount: 18,
    tags: ['product', 'planning'],
  },
  {
    id: 'd3',
    name: 'Research Notes - Neural Networks.txt',
    type: 'txt',
    size: 45824,
    status: 'indexed',
    createdAt: '2025-08-08T11:00:00Z',
    updatedAt: '2025-08-08T11:05:00Z',
    summary: 'In-depth research notes covering transformer architectures, attention mechanisms, and recent advances in LLMs.',
    pageCount: 12,
    tags: ['research', 'ai'],
  },
  {
    id: 'd4',
    name: 'Meeting Minutes - Board Review.pdf',
    type: 'pdf',
    size: 982304,
    status: 'processing',
    createdAt: '2025-08-12T08:00:00Z',
    updatedAt: '2025-08-12T08:02:00Z',
    summary: undefined,
    pageCount: 8,
    tags: ['meetings'],
  },
  {
    id: 'd5',
    name: 'API Architecture Spec.md',
    type: 'md',
    size: 28672,
    status: 'indexed',
    createdAt: '2025-08-07T16:45:00Z',
    updatedAt: '2025-08-07T16:50:00Z',
    summary: 'Technical specification for the BrainDoc API covering endpoints, authentication, and vector storage design.',
    pageCount: 6,
    tags: ['engineering', 'specs'],
  },
  {
    id: 'd6',
    name: 'User Interview Transcript.docx',
    type: 'docx',
    size: 67328,
    status: 'failed',
    createdAt: '2025-08-06T13:15:00Z',
    updatedAt: '2025-08-06T13:20:00Z',
    summary: undefined,
    pageCount: 4,
    tags: ['research', 'ux'],
  },
  {
    id: 'd7',
    name: 'Competitive Analysis Q3.pdf',
    type: 'pdf',
    size: 1536000,
    status: 'indexed',
    createdAt: '2025-08-05T10:30:00Z',
    updatedAt: '2025-08-05T10:40:00Z',
    summary: 'Detailed competitive landscape analysis comparing key competitors across pricing, features, and market positioning.',
    pageCount: 28,
    tags: ['strategy', 'research'],
  },
  {
    id: 'd8',
    name: 'OKR Planning Notes.txt',
    type: 'txt',
    size: 18432,
    status: 'uploading',
    createdAt: '2025-08-12T09:50:00Z',
    updatedAt: '2025-08-12T09:50:00Z',
    summary: undefined,
    pageCount: 3,
    tags: ['planning'],
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'c1',
    title: 'Q3 Revenue Analysis',
    createdAt: '2025-08-10T10:00:00Z',
    updatedAt: '2025-08-10T10:15:00Z',
    messages: [
      {
        id: 'm1',
        role: 'user',
        content: 'What was the total revenue growth in Q3 compared to Q2?',
        createdAt: '2025-08-10T10:00:00Z',
      },
      {
        id: 'm2',
        role: 'assistant',
        content: 'Based on the Q3 Financial Report, total revenue grew by 18.4% compared to Q2, reaching $4.2M. The growth was primarily driven by a 24% increase in enterprise subscriptions and a 12% rise in self-serve plans. The report also notes that customer acquisition cost decreased by 15% while lifetime value increased by 22%.',
        sources: [
          {
            documentId: 'd1',
            documentName: 'Q3 Financial Report.pdf',
            chunkId: 'ch1',
            page: 12,
            text: 'Q3 revenue reached $4.2M, an 18.4% increase from Q2...',
            score: 0.94,
          },
          {
            documentId: 'd1',
            documentName: 'Q3 Financial Report.pdf',
            chunkId: 'ch2',
            page: 15,
            text: 'Enterprise subscriptions grew 24% year-over-year...',
            score: 0.89,
          },
        ],
        createdAt: '2025-08-10T10:00:30Z',
      },
    ],
  },
  {
    id: 'c2',
    title: 'Product Timeline Questions',
    createdAt: '2025-08-09T15:00:00Z',
    updatedAt: '2025-08-09T15:20:00Z',
    messages: [
      {
        id: 'm3',
        role: 'user',
        content: 'When is the voice interaction feature planned for release?',
        createdAt: '2025-08-09T15:00:00Z',
      },
      {
        id: 'm4',
        role: 'assistant',
        content: 'According to the Product Roadmap 2025, voice-based AI interaction is slated for Q4 2025, specifically targeting a November release. It is currently listed as a P1 priority and depends on the completion of the real-time streaming infrastructure planned for October.',
        sources: [
          {
            documentId: 'd2',
            documentName: 'Product Roadmap 2025.docx',
            chunkId: 'ch3',
            page: 7,
            text: 'Voice interaction feature targeting Q4 2025 release...',
            score: 0.91,
          },
        ],
        createdAt: '2025-08-09T15:00:25Z',
      },
    ],
  },
  {
    id: 'c3',
    title: 'Neural Network Research',
    createdAt: '2025-08-08T12:00:00Z',
    updatedAt: '2025-08-08T12:10:00Z',
    messages: [],
  },
];

export const mockSearchResults: SearchResult[] = [
  {
    id: 's1',
    documentId: 'd1',
    documentName: 'Q3 Financial Report.pdf',
    text: 'Revenue growth in Q3 was primarily driven by enterprise subscriptions, which saw a 24% increase year-over-year. The average contract value rose from $12K to $15K, with net revenue retention reaching 118%.',
    page: 12,
    score: 0.94,
    type: 'pdf',
  },
  {
    id: 's2',
    documentId: 'd7',
    documentName: 'Competitive Analysis Q3.pdf',
    text: 'Enterprise subscription growth across the sector averaged 15%, with top quartile companies achieving 20-25% growth. Our 24% growth places us in the top quartile of the competitive set.',
    page: 8,
    score: 0.87,
    type: 'pdf',
  },
  {
    id: 's3',
    documentId: 'd2',
    documentName: 'Product Roadmap 2025.docx',
    text: 'The enterprise tier will receive priority features including advanced analytics, SSO integration, and custom model fine-tuning capabilities designed to drive subscription growth further.',
    page: 5,
    score: 0.81,
    type: 'docx',
  },
  {
    id: 's4',
    documentId: 'd1',
    documentName: 'Q3 Financial Report.pdf',
    text: 'Customer acquisition cost decreased by 15% while lifetime value increased by 22%, resulting in a significantly improved LTV:CAC ratio of 4.2:1, up from 3.1:1 in Q2.',
    page: 15,
    score: 0.78,
    type: 'pdf',
  },
  {
    id: 's5',
    documentId: 'd5',
    documentName: 'API Architecture Spec.md',
    text: 'The subscription management endpoints support tier-based feature gating, allowing enterprise customers to access premium API capabilities including higher rate limits and dedicated support channels.',
    page: 4,
    score: 0.72,
    type: 'md',
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: 'i1',
    name: 'Google Drive',
    description: 'Automatically sync and index documents from your Google Drive folders.',
    icon: 'Drive',
    connected: true,
    category: 'Storage',
  },
  {
    id: 'i2',
    name: 'Gmail',
    description: 'Import and search through important emails and attachments.',
    icon: 'Mail',
    connected: false,
    category: 'Communication',
  },
  {
    id: 'i3',
    name: 'Google Calendar',
    description: 'Connect calendar events and meeting notes for context-aware answers.',
    icon: 'Calendar',
    connected: false,
    category: 'Productivity',
  },
  {
    id: 'i4',
    name: 'Slack',
    description: 'Index Slack messages and threads for team knowledge search.',
    icon: 'MessageSquare',
    connected: false,
    category: 'Communication',
  },
  {
    id: 'i5',
    name: 'Notion',
    description: 'Sync your Notion pages and databases into your knowledge base.',
    icon: 'FileText',
    connected: true,
    category: 'Productivity',
  },
  {
    id: 'i6',
    name: 'Web Search',
    description: 'Enable real-time web search to supplement your knowledge base with current information.',
    icon: 'Globe',
    connected: false,
    category: 'Search',
  },
];

export const mockActivity: ActivityItem[] = [
  {
    id: 'a1',
    type: 'upload',
    title: 'Meeting Minutes - Board Review.pdf',
    description: 'Document uploaded and is currently being processed',
    timestamp: '2025-08-12T08:02:00Z',
  },
  {
    id: 'a2',
    type: 'chat',
    title: 'Q3 Revenue Analysis',
    description: 'Asked about revenue growth comparison',
    timestamp: '2025-08-10T10:15:00Z',
  },
  {
    id: 'a3',
    type: 'index',
    title: 'Competitive Analysis Q3.pdf',
    description: 'Document successfully indexed with 28 pages',
    timestamp: '2025-08-05T10:40:00Z',
  },
  {
    id: 'a4',
    type: 'search',
    title: 'enterprise subscription growth',
    description: 'Found 5 matching results across 3 documents',
    timestamp: '2025-08-11T14:30:00Z',
  },
  {
    id: 'a5',
    type: 'upload',
    title: 'Product Roadmap 2025.docx',
    description: 'Document uploaded and indexed successfully',
    timestamp: '2025-08-09T14:25:00Z',
  },
];
